export default function WaxDescription() {
  return (
    <div className="wax-description lg:pl-24">
      <ul className="wax-list text-xl lg:text-2xl text-center lg:text-left  lg:ml-24">
        <li id="1">Brow Shaping</li>
        <li id="2">Brow Shaping, Lamination & Tint</li>
        <li id="3">Tint</li>
        <li id="4">Lamination</li>
        <li id="5">Tint & Lamination</li>
        <li id="6">Wax & Tint</li>
        <li id="7">Lip & Chin</li>
        <li id="8">Lip</li>
        <li id="9">Chin</li>
        <li id="10">Sideburns</li>
        <li id="11">Full Face</li>
        <li id="12">Nostrils</li>
        <li id="13">W Butt Strip</li>
        <li id="14">Full Butt</li>
        <li id="15">M Butt Strip </li>
        <li id="16">Full Butt</li>
        <li id="17">Underarms</li>
        <li id="18">Full Arms | Half Arms</li>
        <li id="19">Chest</li>
        <li id="20">Stomach</li>
        <li id="21">Full Back</li>
        <li id="22">Upper Back</li>
        <li id="25">Mid Back</li>
        <li id="24">Lower Back</li>
        <li id="25">Shoulders</li>
        <li id="26">Bikini</li>
        <li id="27">Bikini Maintenance</li>
        <li id="28">Bikini Package of 6</li>
        <li id="29">Full Bikini</li>
        <li id="30">Full Bikini Maintenance</li>
        <li id="31">Full Bikini Package of 6</li>
        <li id="32">Brazilian</li>
        <li id="33">Brazilian Maintenance</li>
        <li id="34">Brazilian Package of 6</li>
        <li id="35">Full Legs | Half Legs</li>
      </ul>
      <ul className="wax-list-2 text-xl text-center lg:text-2xl mr-2 lg:ml-24">
        <li id="1"> $20</li>
        <li id="2">$75</li>
        <li id="3">$25</li>
        <li id="4">$50</li>
        <li id="5">$65</li>
        <li id="6">$40</li>
        <li id="7">$22</li>
        <li id="8">$12</li>
        <li id="9">$12</li>
        <li id="10">$15</li>
        <li id="11">$55</li>
        <li id="12">$15</li>
        <li id="13">$20</li>
        <li id="14">$35</li>
        <li id="15">$20</li>
        <li id="16">$40</li>
        <li id="17">$20</li>
        <li id="18">$45 | $30</li>
        <li id="19">$30</li>
        <li id="20">$35</li>
        <li id="21">$55</li>
        <li id="22">$30</li>
        <li id="23">$30</li>
        <li id="24">$20</li>
        <li id="25">$20</li>
        <li id="26">$45</li>
        <li id="27">$35</li>
        <li id="28">$180</li>
        <li id="29">$55</li>
        <li id="30">$45</li>
        <li id="31">$240</li>
        <li id="22">$65</li>
        <li id="33">$55</li>
        <li id="34">$300</li>
        <li id="35">$80 | $50</li>
      </ul>
    </div>
  );
}
